# Generated by Django 4.2.9 on 2024-01-22 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_actor_cinema_hall_movie_showing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieShowtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime_date', models.DateField(default=django.utils.timezone.now)),
                ('showtime_time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.movie')),
            ],
        ),
    ]
