# Generated by Django 4.2.9 on 2024-01-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_movieshowtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieShowtime',
        ),
    ]
