# Generated by Django 4.2.9 on 2024-01-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_delete_movieshowtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image_actor',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='actor_images'),
        ),
    ]
