# Generated by Django 4.2.9 on 2024-01-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_category_alter_actor_name_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='App.category'),
        ),
    ]
