# Generated by Django 4.2.9 on 2024-01-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country_of_origin',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
