# Generated by Django 4.2.9 on 2024-01-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_rename_number_of_tickets_reservation_num_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='num_tickets',
            new_name='number_of_tickets',
        ),
    ]
