# Generated by Django 4.2.9 on 2024-02-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_rename_num_tickets_reservation_number_of_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=8),
        ),
    ]
